// Phase 5: emit the enriched dataset as a generated TypeScript module that the
// web app imports directly (replacing the hand-curated seeds).
//
// Usage: tsx src/emit.ts
// Reads data/enriched/{type}.jsonl, writes apps/web/lib/entities-data.ts

import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { readJsonl } from "./checkpoint";
import type { EnrichedCandidate } from "./enrich";
import type { Interval } from "../../../apps/web/lib/lanes";
import type { TimelineEvent } from "../../../apps/web/lib/types";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, "..", "..", "..", "apps", "web", "lib", "entities-data.ts");

const NOW = new Date().getFullYear();
const FLOOR = -3000; // v1 timeline floor (3000 BCE)
const PERIOD_MIN_SIG = 0.5; // keep the always-on periods band focused
// Minimum rendered span for "instantaneous" entities (e.g. a work dated to a
// single year), so their band has a visible width and can be zoomed into and
// labelled instead of collapsing to a sub-pixel sliver.
const MIN_SPAN_YEARS = 30 / 365.25; // ~one month

const wiki = (title: string) =>
  `https://en.wikipedia.org/wiki/${encodeURIComponent(title.replace(/ /g, "_"))}`;

// Clamp a start year to the timeline floor; null when the entity is entirely
// prehistoric (end before the floor).
function clampInterval(
  r: EnrichedCandidate,
  endFallback: number,
): { startYear: number; endYear: number } | null {
  if (!r.start) return null;
  let startYear = r.start.year;
  let endYear = r.end?.year ?? endFallback;
  if (endYear < FLOOR) return null; // entirely prehistoric
  if (startYear < FLOOR) startYear = FLOOR;
  if (endYear < startYear) endYear = startYear;
  return { startYear, endYear };
}

function toInterval(r: EnrichedCandidate, endFallback: number): Interval | null {
  const span = clampInterval(r, endFallback);
  if (!span) return null;
  if (span.endYear - span.startYear < MIN_SPAN_YEARS) {
    span.endYear = span.startYear + MIN_SPAN_YEARS;
  }
  return {
    id: r.qid,
    title: r.label,
    startYear: span.startYear,
    endYear: span.endYear,
    estimated: r.start?.estimated ?? false,
    description: r.description,
    significance: r.significance,
    wikipediaUrl: wiki(r.wikipediaTitle),
  };
}

async function main() {
  const person = await readJsonl<EnrichedCandidate>("enriched/person.jsonl");
  const state = await readJsonl<EnrichedCandidate>("enriched/state.jsonl");
  const work = await readJsonl<EnrichedCandidate>("enriched/work.jsonl");
  const period = await readJsonl<EnrichedCandidate>("enriched/period.jsonl");
  const war = await readJsonl<EnrichedCandidate>("enriched/war.jsonl");
  const event = await readJsonl<EnrichedCandidate>("enriched/event.jsonl");

  // Lanes: lifespans, state existence, cultural-work creation windows, wars.
  const people = person.map((r) => toInterval(r, NOW)).filter((x): x is Interval => !!x);
  const powers = state.map((r) => toInterval(r, NOW)).filter((x): x is Interval => !!x);
  const culture = work.map((r) => toInterval(r, r.start?.year ?? NOW)).filter((x): x is Interval => !!x);
  // A war with no recorded end is "ongoing" only if it began recently; an old
  // start with no end means the end date is simply missing from Wikidata, so
  // treat it as point-like instead of stretching it to the present.
  const wars = war
    .map((r) => toInterval(r, r.start && r.start.year < NOW - 100 ? r.start.year : NOW))
    .filter((x): x is Interval => !!x);

  // Always-on periods band: significant historical periods only.
  const periods = period
    .filter((r) => r.significance >= PERIOD_MIN_SIG)
    .map((r) => toInterval(r, NOW))
    .filter((x): x is Interval => !!x);

  // Main-axis points: discrete events.
  const asEvent = (r: EnrichedCandidate): TimelineEvent | null => {
    if (!r.start) return null;
    if (r.start.year < FLOOR) return null;
    return {
      id: r.qid,
      year: r.start.year,
      title: r.label,
      description: r.description || r.label,
      significance: r.significance,
      wikipediaUrl: wiki(r.wikipediaTitle),
    };
  };
  const events = event.map(asEvent).filter((x): x is TimelineEvent => !!x);

  const json = (arr: unknown[]) => JSON.stringify(arr, null, 2);

  const content = `// Generated by packages/ingestion/src/emit.ts — do not edit by hand.
// Source: Wikipedia Vital articles → Wikidata → scoring → enrichment.

import type { Interval } from "./lanes";
import type { TimelineEvent } from "./types";

export const PEOPLE: Interval[] = ${json(people)};

export const POWERS: Interval[] = ${json(powers)};

export const CULTURE: Interval[] = ${json(culture)};

export const WARS: Interval[] = ${json(wars)};

export const PERIODS: Interval[] = ${json(periods)};

export const EVENTS: TimelineEvent[] = ${json(events)};
`;

  await writeFile(OUT_PATH, content);
  console.error(
    `wrote ${OUT_PATH}: people=${people.length} powers=${powers.length} culture=${culture.length} ` +
      `wars=${wars.length} periods=${periods.length} events=${events.length}`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
