import type { Interval } from "./lanes";

// Lifespans of famous figures across history. `estimated` marks figures whose
// birth/death years are scholarly approximations rather than firmly dated
// (most ancient and early-medieval figures). Negative years are BCE.
export const PEOPLE: Interval[] = [
  { id: "khufu", title: "Khufu", startYear: -2589, endYear: -2566, estimated: true },
  { id: "hammurabi", title: "Hammurabi", startYear: -1810, endYear: -1750, estimated: true },
  { id: "hatshepsut", title: "Hatshepsut", startYear: -1507, endYear: -1458, estimated: true },
  { id: "akhenaten", title: "Akhenaten", startYear: -1380, endYear: -1336, estimated: true },
  { id: "tutankhamun", title: "Tutankhamun", startYear: -1341, endYear: -1323, estimated: true },
  { id: "ramesses-ii", title: "Ramesses II", startYear: -1303, endYear: -1213, estimated: true },
  { id: "homer", title: "Homer", startYear: -800, endYear: -701, estimated: true },
  { id: "pythagoras", title: "Pythagoras", startYear: -570, endYear: -495, estimated: true },
  { id: "confucius", title: "Confucius", startYear: -551, endYear: -479 },
  { id: "buddha", title: "Siddhartha Gautama", startYear: -563, endYear: -483, estimated: true },
  { id: "socrates", title: "Socrates", startYear: -470, endYear: -399, estimated: true },
  { id: "herodotus", title: "Herodotus", startYear: -484, endYear: -425, estimated: true },
  { id: "hippocrates", title: "Hippocrates", startYear: -460, endYear: -370, estimated: true },
  { id: "plato", title: "Plato", startYear: -428, endYear: -348, estimated: true },
  { id: "aristotle", title: "Aristotle", startYear: -384, endYear: -322 },
  { id: "alexander", title: "Alexander the Great", startYear: -356, endYear: -323 },
  { id: "euclid", title: "Euclid", startYear: -325, endYear: -265, estimated: true },
  { id: "archimedes", title: "Archimedes", startYear: -287, endYear: -212, estimated: true },
  { id: "ashoka", title: "Ashoka", startYear: -304, endYear: -232, estimated: true },
  { id: "hannibal", title: "Hannibal", startYear: -247, endYear: -183 },
  { id: "cicero", title: "Cicero", startYear: -106, endYear: -43 },
  { id: "caesar", title: "Julius Caesar", startYear: -100, endYear: -44 },
  { id: "cleopatra", title: "Cleopatra", startYear: -69, endYear: -30 },
  { id: "augustus", title: "Augustus", startYear: -63, endYear: 14 },
  { id: "jesus", title: "Jesus of Nazareth", startYear: -4, endYear: 30, estimated: true },
  { id: "ovid", title: "Ovid", startYear: -43, endYear: 17 },
  { id: "seneca", title: "Seneca", startYear: -4, endYear: 65, estimated: true },
  { id: "pliny", title: "Pliny the Elder", startYear: 23, endYear: 79 },
  { id: "zhang-heng", title: "Zhang Heng", startYear: 78, endYear: 139 },
  { id: "ptolemy", title: "Ptolemy", startYear: 100, endYear: 170, estimated: true },
  { id: "marcus-aurelius", title: "Marcus Aurelius", startYear: 121, endYear: 180 },
  { id: "galen", title: "Galen", startYear: 129, endYear: 216 },
  { id: "constantine", title: "Constantine", startYear: 272, endYear: 337 },
  { id: "augustine", title: "St Augustine", startYear: 354, endYear: 430 },
  { id: "hypatia", title: "Hypatia", startYear: 355, endYear: 415, estimated: true },
  { id: "attila", title: "Attila the Hun", startYear: 406, endYear: 453, estimated: true },
  { id: "muhammad", title: "Muhammad", startYear: 570, endYear: 632, estimated: true },
  { id: "charlemagne", title: "Charlemagne", startYear: 747, endYear: 814, estimated: true },
  { id: "al-khwarizmi", title: "Al-Khwarizmi", startYear: 780, endYear: 850, estimated: true },
  { id: "avicenna", title: "Avicenna", startYear: 980, endYear: 1037 },
  { id: "william-i", title: "William the Conqueror", startYear: 1028, endYear: 1087 },
  { id: "genghis-khan", title: "Genghis Khan", startYear: 1162, endYear: 1227, estimated: true },
  { id: "aquinas", title: "Thomas Aquinas", startYear: 1225, endYear: 1274 },
  { id: "marco-polo", title: "Marco Polo", startYear: 1254, endYear: 1324 },
  { id: "dante", title: "Dante Alighieri", startYear: 1265, endYear: 1321 },
  { id: "joan-of-arc", title: "Joan of Arc", startYear: 1412, endYear: 1431 },
  { id: "gutenberg", title: "Johannes Gutenberg", startYear: 1400, endYear: 1468, estimated: true },
  { id: "leonardo", title: "Leonardo da Vinci", startYear: 1452, endYear: 1519 },
  { id: "columbus", title: "Christopher Columbus", startYear: 1451, endYear: 1506 },
  { id: "michelangelo", title: "Michelangelo", startYear: 1475, endYear: 1564 },
  { id: "copernicus", title: "Nicolaus Copernicus", startYear: 1473, endYear: 1543 },
  { id: "luther", title: "Martin Luther", startYear: 1483, endYear: 1546 },
  { id: "shakespeare", title: "William Shakespeare", startYear: 1564, endYear: 1616 },
  { id: "galileo", title: "Galileo Galilei", startYear: 1564, endYear: 1642 },
  { id: "descartes", title: "René Descartes", startYear: 1596, endYear: 1650 },
  { id: "newton", title: "Isaac Newton", startYear: 1643, endYear: 1727 },
  { id: "bach", title: "Johann Sebastian Bach", startYear: 1685, endYear: 1750 },
  { id: "voltaire", title: "Voltaire", startYear: 1694, endYear: 1778 },
  { id: "franklin", title: "Benjamin Franklin", startYear: 1706, endYear: 1790 },
  { id: "kant", title: "Immanuel Kant", startYear: 1724, endYear: 1804 },
  { id: "catherine-great", title: "Catherine the Great", startYear: 1729, endYear: 1796 },
  { id: "mozart", title: "Wolfgang Amadeus Mozart", startYear: 1756, endYear: 1791 },
  { id: "napoleon", title: "Napoleon Bonaparte", startYear: 1769, endYear: 1821 },
  { id: "beethoven", title: "Ludwig van Beethoven", startYear: 1770, endYear: 1827 },
  { id: "lincoln", title: "Abraham Lincoln", startYear: 1809, endYear: 1865 },
  { id: "darwin", title: "Charles Darwin", startYear: 1809, endYear: 1882 },
  { id: "marx", title: "Karl Marx", startYear: 1818, endYear: 1883 },
  { id: "nightingale", title: "Florence Nightingale", startYear: 1820, endYear: 1910 },
  { id: "marie-curie", title: "Marie Curie", startYear: 1867, endYear: 1934 },
  { id: "gandhi", title: "Mahatma Gandhi", startYear: 1869, endYear: 1948 },
  { id: "einstein", title: "Albert Einstein", startYear: 1879, endYear: 1955 },
  { id: "mandela", title: "Nelson Mandela", startYear: 1918, endYear: 2013 },
  { id: "hawking", title: "Stephen Hawking", startYear: 1942, endYear: 2018 },
];
